export enum ELinks {
    main = '/',
    login = '/login',
    register = '/register',
    verificationLink = '/auth/verify-email',
    forgotPassword = '/auth/reset-password',
    authGoogle = '/auth/callback/google',
    accountManageData = '/account',
    accountPlan = '/account/plan',
    accountBilling = '/account/billing',
    accountNFT = '/account/NFT',
    accountSettings = '/account/settings',
    projects = '/projects',
    diagram = '/diagram',
    team = '/team',
}
