export enum ELinks {
    main = '/',
    login = '/login',
    register = '/register',
    verificationLink = '/verificationLink',
    forgotPassword = '/forgotPassword',
    authGoogle = '/auth/callback/google',
    accountManageData = '/account',
    accountPlan = '/account/plan',
    accountBilling = '/account/billing',
    accountNFT = '/account/NFT',
    accountSettings = '/account/settings',
    dashboard = '/dashboard',
    diagram = '/diagram',
}
